### ISSUE TITLE
Uncaught AssertionError: Unable to add an error, `line` should be a number greater than 0 but und...

### ISSUE THREAD

**Issue by Chris54721** [AtomLinter/linter-jscs#133]
How to reproduce:
1. Open a long file in the editor (mine is ~44k lines, don't know if it's related)
2. Save the file with the `fixOnSave` option enabled

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.2.0

### Stack Trace

Uncaught AssertionError: Unable to add an error, `line` should be a number greater than 0 but undefined given

```
At assert.js:89

AssertionError: Unable to add an error, `line` should be a number greater than 0 but undefined given
    at Object.Errors._validateInput (/Users/chris54721/.atom/packages/linter-jscs/node_modules/jscs/lib/errors.js:69:9)
    at Object.Errors.add (/Users/chris54721/.atom/packages/linter-jscs/node_modules/jscs/lib/errors.js:46:14)
    at [object Object].StringChecker._addParseError (/Users/chris54721/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:212:16)
    at [object Object].<anonymous> (/Users/chris54721/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:254:22)
    at Array.forEach (native)
    at [object Object].StringChecker.fixString (/Users/chris54721/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:253:25)
    at Function.fixString (/Users/chris54721/.atom/packages/linter-jscs/index.js:148:33)
    at /Users/chris54721/.atom/packages/linter-jscs/index.js:80:18
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
     -9:24.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -9:23.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -9:22.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:19.3.0 core:copy (atom-text-editor.editor.is-focused)
     -6:48.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -6:48 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:47.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:39.5.0 core:copy (atom-text-editor.editor.is-focused)
     -3:55.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -3:54.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:54.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -3:53.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:48.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -3:48.6.0 core:cancel (atom-text-editor.editor.is-focused)
  5x -2:47.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:47 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "welcome",
      "spell-check"
    ]
  },
  "linter-jscs": {
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0
color-picker, v2.0.13
file-icons, v1.6.12
language-docker, v1.1.3
language-nginx, v0.6.1
linter, v1.11.2
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-javac, v1.3.0
linter-jscs, v3.2.0
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-phpcs, v1.3.0
linter-scss-lint, v2.4.0
linter-shellcheck, v1.0.2
minimap, v4.16.2
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Looks like this is an internal `jscs` error, does it work from the command line on that file?

**Comment by Chris54721** [comment]
Running `jscs -x filename.js` does work in a terminal. Atom either freezes when saving or throws that error.

**Comment by Arcanemagus** [comment]
Are you able to share a file that reproduces this?

**Comment by casesandberg** [comment]
Are you still having problems with this? I cant seem to reproduce it.

**Comment by Chris54721** [comment]
Can't seem to reproduce as well with jscs 2.8.0, closing.
