### ISSUE TITLE
Error when deleting quote mark

### ISSUE THREAD

**Issue by ricardograca** [AtomLinter/linter-jscs#163]
With a file with these contents:

```js
var testError = 'image/png'
```

If I delete the first quote mark Atom pops up an error message that says:

```
Error: Column start (27) greater than line length (26)
Error: Column start (27) greater than line length (26)
    at Object.rangeFromLineNumber (/home/ricardo/.atom/packages/linter-erb/node_modules/atom-linter/lib/helpers.js:173:11)
    at /home/ricardo/.atom/packages/linter-jscs/src/linter-jscs.js:137:33
    at Array.map (native)
    at Object.lint (/home/ricardo/.atom/packages/linter-jscs/src/linter-jscs.js:134:39)
    at promises.push.Promise.then._this.emitter.emit.linter (/home/ricardo/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /home/ricardo/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/home/ricardo/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /home/ricardo/.atom/packages/linter/lib/linter.coffee:98:16
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /home/ricardo/.atom/packages/linter/lib/editor-linter.js:80:22
    at /home/ricardo/.atom/packages/linter/lib/helpers.coffee:23:18
```

I'm pretty sure this wasn't happening a few days ago, so maybe there was an update to either linter or linter-jscs that is causing this.

**Comment by Arcanemagus** [comment]
It's possible an update to one of your plugins finally brought you to a version of the `atom-linter` helper module that complains about this, I'll look into this shortly.

**Comment by Arcanemagus** [comment]
Reproduced it, looking into the cause.

**Comment by Arcanemagus** [comment]
Looks like this is a bug in `jscs`:
![image](https://cloud.githubusercontent.com/assets/427137/12499121/a4523cfa-c05c-11e5-9e07-eb2a9cb5c639.png)
![image](https://cloud.githubusercontent.com/assets/427137/12499211/6baddc78-c05d-11e5-8604-c572d4358da9.png)
