### ISSUE TITLE
JSON file hashmap trailing comma throws error

### ISSUE THREAD

**Issue by efuquen** [AtomLinter/linter-jscs#165]
1. I save a `package.json` file that has a hashmap with a trailing comma, example like so:

```
"aliases": {
  "electron": "chrometron",
}
```

2. Atom throws an error, with stack trace details below.

If I remove the trailing command and re-save the linter won't throw an error.  I would expect the linter to give me a warning about adding a trailing comma to a json file, which is an error, unlike with a javascript file.

**Atom Version**: 1.4.0
**System**: Ubuntu 15.10
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.4.1

### Stack Trace

Uncaught Error: Parse error on line 15:
...ometron"    }  },}
--------------------^
Expecting 'STRING', got '}'

```
At /usr/share/atom/resources/app.asar/src/pane.js:829

Error: Parse error on line 15:
...ometron"    }  },}
--------------------^
Expecting 'STRING', got '}'
    at Object.parseError (/home/efuquen/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/home/efuquen/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/home/efuquen/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/home/efuquen/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/home/efuquen/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /home/efuquen/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/home/efuquen/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/home/efuquen/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/home/efuquen/.atom/packages/linter-jscs/src/linter-jscs.js:155:23)
    at /home/efuquen/.atom/packages/linter-jscs/src/linter-jscs.js:81:29
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:602:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:643:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:15.4.0 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:15.1.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:14.9.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:14.5.0 vim-mode:move-to-last-character-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:14.2.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:13.2.0 vim-mode:replace (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:13.2.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:12.6.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:12.1.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:08.6.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:05.5.0 vim-mode:activate-characterwise-visual-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 10x -0:05.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:03.6.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  5x -0:02.8.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  2x -0:01.2.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.6.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.3
atom-ternjs, v0.13.2
autoclose-html, v0.19.0
browser-plus, v0.0.54
clipboard-plus, v0.5.1
emmet, v2.3.18
hidpi, v0.11.0
highlight-selected, v0.11.1
language-ansible, v0.1.3
language-latex, v0.6.1
language-rust, v0.4.5
latex, v0.28.2
linter, v1.11.3
linter-clang, v3.3.0
linter-jscs, v3.4.1
linter-rust, v0.3.0
minimap, v4.19.0
minimap-highlight-selected, v4.3.1
pdf-view, v0.39.0
racer, v0.17.2
remote-edit, v1.8.23
rust-api-docs-helper, v0.5.1
symbol-gen, v1.0.0
symbols-tree-view, v0.11.0
term3, v0.21.0
vim-mode, v0.64.0
vim-mode-clipboard-plus, v0.2.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
"linter-jscs" should never run on that file in the first place, as it claims to only support `source.js` and `source.js.jsx` scopes, did you manually change the type of the file to Javascript from JSON?

**Comment by casesandberg** [comment]
Marking as closed. If you add more info please re-open the issue.
