### ISSUE TITLE
Failed to activate the linter-jscs package

### ISSUE THREAD

**Issue by ashleahhill** [AtomLinter/linter-jscs#166]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.4.1

### Stack Trace

Failed to activate the linter-jscs package

```
At packageName is required

Error: packageName is required
    at Object.install (/Users/ashleahhill/.atom/packages/linter-jscs/node_modules/atom-package-deps/lib/main.js:19:27)
    at Function.activate (/Users/ashleahhill/.atom/packages/linter-jscs/src/linter-jscs.js:75:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "linter-jscs": {}
}
```

### Installed Packages

```coffee
# User
docblockr, v0.7.3
editorconfig, v1.2.4
formatter-coffeescript, v0.1.1
git-diff-details, v0.21.0
jshint, v1.8.3
linter, v1.11.3
linter-jscs, v3.4.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Are you seeing this on every Atom launch?

**Comment by repsac-by** [comment]
this happens with any change javascript code
![2016-01-23 12-03-35](https://cloud.githubusercontent.com/assets/4984191/12529499/c1e1e392-c1c9-11e5-9df2-ea0e1d51f5af.png)

**Comment by Arcanemagus** [comment]
@repsac-by That's a completely separate issue, can you file a new issue with a file that reproduces that for you?

**Comment by Voronenko** [comment]
I got the same issue - atom @ ubuntu 14.04 during package "update all" through atom UI
Issue goes away on first Atom restart.

**Comment by steak3** [comment]
Same as Voronenko, but in atom @ Windows 10 x64, after updating 3.4.1 to 3.4.4:
`Cannont find module 'atom-package-path'`

**Comment by casesandberg** [comment]
Can you upgrade to the latest version and see if it is still giving you issues?

**Comment by Arcanemagus** [comment]
Marking this as closed, if uninstalling and re-installing the package, then restarting Atom doesn't solve this for you please file a new issue.

(The documented issue above is a problem with Atom's package installation process failing to work properly, not something wrong with this package.)
