### ISSUE TITLE
`Esnext` setting ignored 

### ISSUE THREAD

**Issue by workmanw** [AtomLinter/linter-jscs#168]
As requested by: @Arcanemagus, I've split this issue from: https://github.com/AtomLinter/linter-jscs/issues/167#issuecomment-174783945 

It seems that the `Esnext` setting on the settings page is being ignored. See screenshots below. 

One thing worth mentioning is that `esnext` was not set in my .jscsrc config. When I added `"esnext": true` to that config, this atom linter did switch over to using babel. Evidence of this was a different config at the breakpoint and issue #167 began working again.

Please let me know if there is any further information I can provide. Happy to also test out any changes. 

--------

**Settings:**
![image](https://cloud.githubusercontent.com/assets/825487/12571020/efa9e7e2-c3aa-11e5-8bbf-1c26adc0c97b.png)

----

**Breakpoint:**
![image](https://cloud.githubusercontent.com/assets/825487/12571100/94092514-c3ab-11e5-95db-c34ea2ae88c6.png)

**Comment by casesandberg** [comment]
Ah! It was originally overriting local settings if you had a `.jscsrc` file. It now merges them so it will honor the esnext setting!

Upgrade to `linter-jscs@3.4.2`

**Comment by workmanw** [comment]
I'll give it a shot. Thank you!

**Comment by casesandberg** [comment]
Sorry, looks like I never pushed this to up to atom, if you upgrade to `linter-jscs@3.4.4` it will have this fix in it

**Comment by workmanw** [comment]
@casesandberg So I updated to 3.4.4 to test and confirm the fix for you, but now my linter is completely broken :( . Every save results in an error. I tried changing the ESNext setting

Here is the stack:
```
AssertionError: `plugin` should be a function
    at NodeConfiguration.Configuration._loadPlugin (/Users/wesley/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:571:5)
    at NodeConfiguration._loadPlugin (/Users/wesley/.atom/packages/linter-jscs/node_modules/jscs/lib/config/node-configuration.js:138:48)
    at NodeConfiguration.<anonymous> (/Users/wesley/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:495:18)
    at Array.forEach (native)
    at NodeConfiguration.Configuration._processConfig (/Users/wesley/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:494:25)
    at NodeConfiguration.Configuration.load (/Users/wesley/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:238:10)
    at [object Object].StringChecker.configure (/Users/wesley/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:67:29)
    at [object Object].Checker.configure (/Users/wesley/.atom/packages/linter-jscs/node_modules/jscs/lib/checker.js:28:39)
    at Object.lint (/Users/wesley/.atom/packages/linter-jscs/src/linter-jscs.js:123:19)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/wesley/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/wesley/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/wesley/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/wesley/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/wesley/.atom/packages/linter/lib/editor-linter.js:80:22
    at /Users/wesley/.atom/packages/linter/lib/helpers.coffee:23:18
```

In a screenshot:
<img width="464" alt="screen shot 2016-02-06 at 1 18 11 pm" src="https://cloud.githubusercontent.com/assets/825487/12868410/266f3ee4-ccd4-11e5-936a-ba8eaa376b55.png">

Should I open a new issue for this? Is there an easy way for me to go back a version?
