### ISSUE TITLE
Uncaught Error: Parse error on line 17:...oment": "2.11.2",  },  "engines": { -----------------...

### ISSUE THREAD

**Issue by tambovchanin** [AtomLinter/linter-jscs#181]
Try to write

var  moment = require('moment');

and save generate exception

**Atom Version**: 1.5.1
**System**: Mac OS X 10.11
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.4.5

### Stack Trace

Uncaught Error: Parse error on line 17:
...oment": "2.11.2",  },  "engines": { 
----------------------^
Expecting 'STRING', got '}'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:825

Error: Parse error on line 17:
...oment": "2.11.2",  },  "engines": { 
----------------------^
Expecting 'STRING', got '}'
    at Object.parseError (/Users/denishiryaev/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/Users/denishiryaev/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/Users/denishiryaev/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/Users/denishiryaev/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/Users/denishiryaev/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /Users/denishiryaev/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/Users/denishiryaev/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/Users/denishiryaev/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/Users/denishiryaev/.atom/packages/linter-jscs/src/linter-jscs.js:175:23)
    at /Users/denishiryaev/.atom/packages/linter-jscs/src/linter-jscs.js:83:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:47 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:29.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:26.8.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:24.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:22.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:55.4.0 core:copy (atom-text-editor.editor.is-focused)
     -1:51.1.0 core:paste (atom-text-editor.editor.is-focused)
     -1:28.7.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -1:28.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:27.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:27.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:27 core:backspace (atom-text-editor.editor.is-focused)
  5x -1:26.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:21.6.0 core:copy (atom-text-editor.editor.is-focused)
     -0:20.6.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:20.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      ".idea",
      ".settings",
      "node_modules"
    ],
    "projectHome": "/Users/denisshiryaev/Documents/Sources/noodoo",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "linter-jscs": {
    "fixOnSave": true,
    "preset": "google"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-beautify, v0.28.22
atom-jade, v0.3.0
atom-jshint, v2.0.0
jade-bootstrap3-snippets, v0.3.0
jshint, v1.8.3
linter, v1.11.3
linter-jade, v0.3.2
linter-jscs, v3.4.5
linter-jshint, v1.3.0
local-history, v3.2.3
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-linter, v1.1.1

# Dev
No dev packages
```

**Comment by tambovchanin** [comment]
This is my error in package.json file

**Comment by casesandberg** [comment]
Ah, this was actually a bug in the old version of the package you are using as well. If you upgrade to 1.5.5 you shouldn't see that again!

**Comment by Arcanemagus** [comment]
Marking as a duplicate of #257.
