### ISSUE TITLE
I am starting to use Atom and installed this plugin

### ISSUE THREAD

**Issue by Dindaleon** [AtomLinter/linter-jscs#185]
I am totally lost here, please help. Here is the bug report: 

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Unknown Windows Version
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.4.6

### Stack Trace

Uncaught Error: Parse error on line 5:
...IONS_AUTH_PATH"]
  "requireCurlyBraces"
----------------------^
Expecting 'EOF', '}', ',', ']', got 'STRING'

```
At C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\src\pane.js:825

Error: Parse error on line 5:
...IONS_AUTH_PATH"]
  "requireCurlyBraces"
----------------------^
Expecting 'EOF', '}', ',', ']', got 'STRING'
    at Object.parseError (C:\Users\RustyCool\.atom\packages\linter-jscs\node_modules\jscs\node_modules\jsonlint\lib\jsonlint.js:55:11)
    at Object.parse (C:\Users\RustyCool\.atom\packages\linter-jscs\node_modules\jscs\node_modules\jsonlint\lib\jsonlint.js:132:22)
    at exports.parse (C:\Users\RustyCool\.atom\packages\linter-jscs\node_modules\jscs\node_modules\jsonlint\lib\jsonlint.js:417:53)
    at Object.exports.getContent (C:\Users\RustyCool\.atom\packages\linter-jscs\node_modules\jscs\lib\cli-config.js:88:31)
    at Object.exports.load (C:\Users\RustyCool\.atom\packages\linter-jscs\node_modules\jscs\lib\cli-config.js:139:20)
    at Function.getConfig (C:/Users/RustyCool/.atom/packages/linter-jscs/src/linter-jscs.js:199:23)
    at C:/Users/RustyCool/.atom/packages/linter-jscs/src/linter-jscs.js:84:31
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\src\text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\src\pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\src\pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\src\workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\src\register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\RustyCool\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:03.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
language-babel, v2.15.4
linter, v1.11.3
linter-eslint, v6.0.0
linter-jscs, v3.4.6

# Dev
No dev packages
```

**Comment by Dindaleon** [comment]
Just solved it, there was a comma missing in the config file for jscs.

**Comment by Arcanemagus** [comment]
Ah ha, and here I thought the bug where `jscs` decided it could lint JSON was back, glad you got it figured out!
