### ISSUE TITLE
TypeError: Object.assign is not a function

### ISSUE THREAD

**Issue by Kreozot** [AtomLinter/linter-jscs#191]
### Version
3.4.6 (Atom 1.0.19, Windows 10 x64)

### Issue

When I open any JS file I get the error:
```
TypeError: Object.assign is not a function
  at Object.lint (C:\Users\s.sharov\.atom\packages\linter-jscs\src\linter-jscs.js:98:54)
  at promises.push.Promise.then._this.emitter.emit.linter (C:\Users\s.sharov\.atom\packages\linter\lib\linter-registry.js:95:28)
  at C:\Users\s.sharov\.atom\packages\linter\lib\linter-registry.js:94:25
  at Set.forEach (native)
  at LinterRegistry.lint (C:\Users\s.sharov\.atom\packages\linter\lib\linter-registry.js:92:20)
  at C:\Users\s.sharov\.atom\packages\linter\lib\linter.coffee:98:16
  at Emitter.module.exports.Emitter.emit (C:\Users\s.sharov\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\s.sharov\.atom\packages\linter\lib\editor-linter.js:100:23
  at C:\Users\s.sharov\.atom\packages\linter\lib\helpers.coffee:23:18
```

**Comment by Kreozot** [comment]
Yeah, my node version is 0.12.7, so it doesn't support Object.assign. Is this the reason? Maybe use a polyfill?

**Comment by Kreozot** [comment]
Okay, I see 'use babel' directive. So, maybe it is on Atom side then?

**Comment by Kreozot** [comment]
Okay, I tried it: [object-assign ponyfill](https://www.npmjs.com/package/object-assign) did the trick. Should I make a PR?

**Comment by Arcanemagus** [comment]
Your Atom version is _very_ out of date, which is the reason you hit this.

**Comment by Kreozot** [comment]
@Arcanemagus, looks like you're right. I just figured out that my Atom was unable to find updates - that's why I was thinking that it is a latest version.

**Comment by Arcanemagus** [comment]
Yea, it was somewhere late in the v1.0.x time that autoupdates broke for a bit :disappointed:.
