### ISSUE TITLE
Uncaught Error: Parse error on line 1:^Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', ...

### ISSUE THREAD

**Issue by nlhuykhang** [AtomLinter/linter-jscs#199]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.4.8

### Stack Trace

Uncaught Error: Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:825

Error: Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'
    at Object.parseError (/Users/khangnlh/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/Users/khangnlh/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/Users/khangnlh/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/Users/khangnlh/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/Users/khangnlh/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /Users/khangnlh/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/Users/khangnlh/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/Users/khangnlh/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/Users/khangnlh/.atom/packages/linter-jscs/src/linter-jscs.js:194:23)
    at /Users/khangnlh/.atom/packages/linter-jscs/src/linter-jscs.js:85:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1045:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:08.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:08.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:03.0 core:save (atom-text-editor.editor.is-focused)
  5x -0:02.8.0 core:move-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "linter-tidy",
      "linter-htmlhint",
      "linter-bootlint",
      "sourcegraph-atom",
      "linter-handlebars",
      "jshint"
    ],
    "excludeVcsIgnoredPaths": false,
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/khangnlh/DSV"
  },
  "linter-jscs": {}
}
```

### Installed Packages

```coffee
# User
Handlebars, v1.4.1
atom-beautify, v0.28.24
atom-handlebars, v1.3.0
atom-jade, v0.3.0
file-icons, v1.6.17
hyperclick, v0.0.35
js-hyperclick, v1.4.1
last-cursor-position, v0.9.0
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-jscs, v3.4.8
linter-jshint, v2.0.2
linter-jsxhint, v0.1.2
minimap, v4.19.0
react, v0.14.1
tabs-to-spaces, v1.0.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
What does your `jscs` configuration look like?

**Comment by Arcanemagus** [comment]
Closing due to lack of response.

**Comment by Arcanemagus** [comment]
Marking as a duplicate of #257.
