### ISSUE TITLE
Uncaught Error: Parse error on line 21:...witch": "^4.0.2",  }}----------------------^Expectin...

### ISSUE THREAD

**Issue by tap52384** [AtomLinter/linter-jscs#202]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.4.9

### Stack Trace

Uncaught Error: Parse error on line 21:
...witch": "^4.0.2",  }}
----------------------^
Expecting 'STRING', got '}'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:825

Error: Parse error on line 21:
...witch": "^4.0.2",  }}
----------------------^
Expecting 'STRING', got '}'
    at Object.parseError (/Users/patricklewis/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/Users/patricklewis/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/Users/patricklewis/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/Users/patricklewis/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/Users/patricklewis/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /Users/patricklewis/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/Users/patricklewis/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/Users/patricklewis/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/Users/patricklewis/.atom/packages/linter-jscs/src/linter-jscs.js:201:27)
    at /Users/patricklewis/.atom/packages/linter-jscs/src/linter-jscs.js:89:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1045:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:28.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:27.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:26.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:26.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:26.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:19.7.0 core:paste (atom-text-editor.editor.is-focused)
  5x -0:18.9.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -0:17.2.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:12.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:12.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:09.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:03.2.0 core:cancel (atom-text-editor.editor.is-focused)
  4x -0:01.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "toothpaste"
    ]
  },
  "linter-jscs": {
    "disallowTrailingComma": true,
    "preset": "jquery",
    "requireCamelCaseOrUpperCaseIdentifiers": true,
    "requireTrailingComma": false,
    "validateQuoteMarks": {
      "escape": true,
      "mark": "'"
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.26
color-picker, v2.1.1
compare-files, v0.6.2
file-icons, v1.6.18
language-htaccess, v0.1.1
linter, v1.11.3
linter-jscs, v3.4.9
linter-jshint, v2.0.3
linter-markdown, v1.5.0
linter-php, v1.2.0
linter-phpcs, v1.3.1
linter-phpmd, v1.4.1
linter-scss-lint, v2.5.1
linter-xmllint, v1.3.4
minimap, v4.21.0
project-manager, v2.7.6
react, v0.14.1
toothpaste, v1.0.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
I'm guessing this was an invalid `.jscsrc` file?

**Comment by tap52384** [comment]
I believe so. That's why I closed it.

**Comment by Arcanemagus** [comment]
Marking as a duplicate of #257.
