### ISSUE TITLE
Uncaught Error: Parse error on line 1:^Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', ...

### ISSUE THREAD

**Issue by astoilkov** [AtomLinter/linter-jscs#205]
**Atom Version**: 1.6.0
**System**: Mac OS X 10.9.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.4.10

### Stack Trace

Uncaught Error: Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:896

Error: Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'
    at Object.parseError (/Users/astoilkov/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/Users/astoilkov/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/Users/astoilkov/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/Users/astoilkov/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/Users/astoilkov/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /Users/astoilkov/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/Users/astoilkov/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/Users/astoilkov/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/Users/astoilkov/.atom/packages/linter-jscs/src/linter-jscs.js:201:27)
    at /Users/astoilkov/.atom/packages/linter-jscs/src/linter-jscs.js:89:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1051:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:629:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:613:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:596:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:673:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:205:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:03.8.0 core:close (div.panels-item)
     -0:02.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-wallaby",
      "atom-typescript",
      "emmet"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "linter-jscs": {
    "displayAs": "warning",
    "onlyConfig": true
  }
}
```

### Installed Packages

```coffee
# User
last-cursor-position, v0.9.0
linter, v1.11.4
linter-csslint, v1.3.2
linter-jscs, v3.4.10
linter-jshint, v2.0.3
pigments, v0.25.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Looks like you have an invalid `.jscsrc` file, from the looks of it I'm guessing you have a trailing `,` that shouldn't be there. `.jscsrc` files _must_ be valid JSON.

**Comment by astoilkov** [comment]
Nope. I don't have any `.jscsrc` in the project.

**Comment by Arcanemagus** [comment]
The error is being thrown from `jscs`'s `cli-config.js` attempting to run the configuration through it's sub-module of `jsonlint` and failing... so you have an invalid `.jscsrc` file _somewhere_ in one of the parent directories of the project. (`jscs` will search up to the root of the file system for a configuration)

**Comment by astoilkov** [comment]
Ok. I found the problem. I had an empty `package.json` file in a parent directory not part of the project. Don't you think this is somewhat unexpected behavior which causes undesired user experience as I wasn't able to save my file because of the error?

**Comment by Arcanemagus** [comment]
The file should still save as this package has nothing to do with that, all it does is report errors and issues from `jscs` inside Atom.

If the file didn't save there is something else majorly wrong with your system (permissions issue?).

As for the error it could probably be handled better, I'm glad you were able to find the cause.

**Comment by astoilkov** [comment]
As soon as I disabled the linter-jscs extension the file started saving.

**Comment by Arcanemagus** [comment]
Marking as a duplicate of #257.

**Comment by akashmittal5432** [comment]
Error: Parse error on line 1:
\"update\":true,\"r
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
