### ISSUE TITLE
Uncaught Error: Parse error on line 24:...p-bower": "0.0.13",<<<<<<< Updated upst--------------...

### ISSUE THREAD

**Issue by skoblenick** [AtomLinter/linter-jscs#215]
[Enter steps to reproduce below:]

1. Open gulpfile.js
2. Change line
3. Save

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.5.0

### Stack Trace

Uncaught Error: Parse error on line 24:
...p-bower": "0.0.13",<<<<<<< Updated upst
----------------------^
Expecting 'STRING', got 'undefined'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:896

Error: Parse error on line 24:
...p-bower": "0.0.13",<<<<<<< Updated upst
----------------------^
Expecting 'STRING', got 'undefined'
    at Object.parseError (/Users/rskoblenick/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/Users/rskoblenick/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/Users/rskoblenick/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/Users/rskoblenick/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/Users/rskoblenick/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /Users/rskoblenick/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/Users/rskoblenick/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/Users/rskoblenick/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/Users/rskoblenick/.atom/packages/linter-jscs/src/linter-jscs.js:214:27)
    at /Users/rskoblenick/.atom/packages/linter-jscs/src/linter-jscs.js:89:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1051:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:629:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:613:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:596:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:673:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:205:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  3x -0:51 core:backspace (atom-text-editor.editor.is-focused)
     -0:47.7.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:20.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:03.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jshint",
      "linter-jsxhint",
      "linter-markdownlint"
    ]
  },
  "linter-jscs": {
    "preset": "google"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-beautify, v0.29.2
autocomplete-angular-material, v0.4.0
editorconfig, v1.2.4
gradle-ci, v1.1.4
jshint, v1.8.5
language-gradle, v0.0.3
language-groovy, v0.6.0
linter, v1.11.4
linter-erb, v1.0.2
linter-javac, v1.8.1
linter-js-yaml, v1.2.5
linter-jscs, v3.5.0
linter-jsonlint, v1.2.2
linter-less, v2.4.2
linter-pep8, v1.2.1
linter-tidy, v2.1.0
omni-ruler, v0.4.2
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by skoblenick** [comment]
Spotted the issue is in the package.json there were some conflicts which break the linter.

**Comment by Arcanemagus** [comment]
As it looks like you already correctly deduced, this is what happens when your `package.json` isn't valid JSON.

**Comment by Arcanemagus** [comment]
Marking as a duplicate of #257.
