### ISSUE TITLE
Uncaught Error: Parse error on line 23:...rver": "^1.14.1",  }}----------------------^Expectin...

### ISSUE THREAD

**Issue by VDUCHEW** [AtomLinter/linter-jscs#217]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.5.0

### Stack Trace

Uncaught Error: Parse error on line 23:
...rver": "^1.14.1",  }}
----------------------^
Expecting 'STRING', got '}'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:896

Error: Parse error on line 23:
...rver": "^1.14.1",  }}
----------------------^
Expecting 'STRING', got '}'
    at Object.parseError (/Users/tpguser/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/Users/tpguser/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/Users/tpguser/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/Users/tpguser/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/Users/tpguser/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /Users/tpguser/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/Users/tpguser/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/Users/tpguser/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/Users/tpguser/.atom/packages/linter-jscs/src/linter-jscs.js:214:27)
    at /Users/tpguser/.atom/packages/linter-jscs/src/linter-jscs.js:89:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1051:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:629:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:613:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:596:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:673:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:205:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:36.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:36 core:save (atom-text-editor.editor.is-focused)
     -2:34.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:34.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:01.9.0 core:close (atom-text-editor.editor.is-focused)
     -2:00.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:41.3.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:41 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:40.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:30.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:28.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:28.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:15.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:13.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.2
auto-indent, v0.5.0
autoclose-html, v0.23.0
file-icons, v1.7.1
language-javascript-jsx, v0.3.7
linter-jscs, v3.5.0
linter-jshint, v2.1.0
pigments, v0.26.0
react-snippets, v0.4.2
remote-edit, v1.8.24

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
You have invalid JSON in your `package.json`, looks like a trailing `,` snuck in there. Clean that up and it should go away.

**Comment by casesandberg** [comment]
Sorry @Arcanemagus I have been off the grid. Going to get back into the swing of things starting this weekend. I also want to get a specific error in there because we get a ton of these.

**Comment by Arcanemagus** [comment]
We should probably just put in a regex that matches on this and put an error message out (with no range) stating that the JSON file is invalid.

`jscs` seems to run a `json-lint` on the `package.json` and blow completely up when it finds an issue.

**Comment by VDUCHEW** [comment]
Awesome, thanks!

**Comment by Arcanemagus** [comment]
Marking as a duplicate of #257.
