### ISSUE TITLE
Uncaught Error: Parse error on line 7:... server.js"        "test": "echo \"Erro---------------...

### ISSUE THREAD

**Issue by fzxt** [AtomLinter/linter-jscs#222]
Not sure why this is happening.

here is the file it's happening on:

```javascript
var express = require('express');
```

**Atom Version**: 1.8.0-beta1
**System**: Mac OS X 10.11.4
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.5.0

### Stack Trace

Uncaught Error: Parse error on line 7:
... server.js"        "test": "echo \"Erro
----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'STRING'

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:1002

Error: Parse error on line 7:
... server.js"        "test": "echo \"Erro
----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'STRING'
    at Object.parseError (/Users/fzxt/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/Users/fzxt/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/Users/fzxt/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/Users/fzxt/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/Users/fzxt/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /Users/fzxt/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/Users/fzxt/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/Users/fzxt/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/Users/fzxt/.atom/packages/linter-jscs/src/linter-jscs.js:214:27)
    at /Users/fzxt/.atom/packages/linter-jscs/src/linter-jscs.js:89:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1074:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:02.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jade"
    ],
    "themes": [
      "one-dark-ui",
      "base16-syntax"
    ]
  },
  "linter-jscs": {
    "esnext": true,
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.2
atom-jade, v0.3.0
atom-ternjs, v0.13.2
autocomplete-modules, v1.4.1
base16-syntax, v1.7.0
color-picker, v2.1.1
emmet, v2.4.3
file-type-icons, v1.0.1
language-javascript-jsx, v0.3.7
linter, v1.11.4
linter-eslint, v7.2.0
linter-jscs, v3.5.0
linter-jshint, v2.1.0
minimap, v4.21.0
pigments, v0.26.0
react, v0.15.0
refactor, v0.6.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
You have invalid JSON in your `package.json`, looks like a missing comma between the line ending in `server.js"` and the one starting with `"test": "echo \"Erro`.

**Comment by fzxt** [comment]
ah that was silly. thanks

**Comment by Arcanemagus** [comment]
Marking as a duplicate of #257.
