### ISSUE TITLE
Uncaught Error: Config values to remove in 3.0:The `esnext` option is enabled by default.The `v...

### ISSUE THREAD

**Issue by adambuczynski** [AtomLinter/linter-jscs#230]
1. Trying to save a file

**Atom Version**: 1.8.0-beta3
**System**: Mac OS X 10.11.2
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.0

### Stack Trace

Uncaught Error: Config values to remove in 3.0:
The `esnext` option is enabled by default.
The `verbose` option is enabled by default.

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:1002

Error: Config values to remove in 3.0:
The `esnext` option is enabled by default.
The `verbose` option is enabled by default.
    at NodeConfiguration.Configuration._errorOnRemovedOptions (/Users/Adam/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:401:15)
    at NodeConfiguration.Configuration._processConfig (/Users/Adam/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:420:10)
    at NodeConfiguration.Configuration.load (/Users/Adam/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:203:10)
    at [object Object].StringChecker.configure (/Users/Adam/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:62:29)
    at [object Object].Checker.configure (/Users/Adam/.atom/packages/linter-jscs/node_modules/jscs/lib/checker.js:28:39)
    at Function.fixString (/Users/Adam/.atom/packages/linter-jscs/src/linter-jscs.js:239:15)
    at /Users/Adam/.atom/packages/linter-jscs/src/linter-jscs.js:95:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:57.5.0 core:copy (atom-text-editor.editor.is-focused)
     -1:55.1.0 core:paste (atom-text-editor.editor.is-focused)
     -1:51 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -1:50.7.0 core:select-down (atom-text-editor.editor.is-focused)
     -1:49.4.0 core:copy (atom-text-editor.editor.is-focused)
     -1:47.4.0 core:paste (atom-text-editor.editor.is-focused)
 11x -1:44 core:select-right (atom-text-editor.editor.is-focused)
     -1:40.1.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:39.7.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -1:39.5.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:36.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:38.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.seti-ui-no-icons)
  2x -0:05.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tabs-to-spaces",
      "autocomplete-css",
      "language-toml",
      "language-ruby-on-rails",
      "language-perl",
      "language-objective-c",
      "language-mustache",
      "language-clojure",
      "language-c",
      "language-csharp",
      "language-java",
      "language-ruby",
      "language-sql",
      "language-source",
      "language-make",
      "language-go"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "._*",
      "bower_components",
      "temp",
      "tmp",
      "fonts"
    ],
    "projectHome": "/Users/Adam/Sites"
  },
  "linter-jscs": {
    "displayAs": "warning",
    "fixOnSave": true,
    "onlyConfig": true,
    "preset": "google"
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.3.0
atom-pair, v2.0.10
atom-text-transformer, v0.7.0
atom-typescript, v8.9.1
autoclose-html, v0.23.0
color-picker, v2.1.1
editorconfig, v1.4.1
file-icons, v1.7.9
git-log, v0.4.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
html-entities, v0.4.0
line-ending-converter, v1.3.2
linter, v1.11.4
linter-jscs, v4.0.0
linter-jshint, v2.1.0
merge-conflicts, v1.4.2
minimap, v4.23.4
minimap-autohide, v0.10.1
node-debugger, v1.4.9
project-manager, v2.9.7
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
As the message says, you need to remove `esnext` from any `jscs` config file in your project with this update since it brings the integrated `jscs` up to v3.

**Comment by adambuczynski** [comment]
I don't have any `esnext` setting in my `.jscsrc`

**Comment by Arcanemagus** [comment]
You have the `verbose` option specified, which is one of the removed values.

**Comment by Arcanemagus** [comment]
Also there was a reason this was a major version update: This is a _breaking_ change, just like the `jscs@3.0.0` update.

**Comment by adambuczynski** [comment]
Ok, thanks.

I still think that there should be a more graceful way of letting Atom users know that some of their config values may need changing. Generally, I don't look at whether or not a package that I'm updating is going to a new major version or not. Often, I have a list of 5-10 packages that need updating at the same time, so I assume everything will just keep working. And I definitely don't expect that after the update I won't be able to save files anymore ;)

Maybe the message should be more clear so the users know that they actually need to do something:

Please remove the following config values from your .jscsrc configuration file:
`esnext` (now enabled by default)
`verbose` (now enabled by default)

**Comment by Arcanemagus** [comment]
That message actually comes direct from `jscs`, we're just displaying it to the user, so blame them for it being unclear (Honestly it should be a regular message with warning severity, not a program error on their part).

If you want to put together a PR that catches that specific error and displays it more gracefully to the user I'd be happy to review it.
