### ISSUE TITLE
Uncaught Error: Config values to remove in 3.0:The `esnext` option is enabled by default.The `v...

### ISSUE THREAD

**Issue by aklkv** [AtomLinter/linter-jscs#231]
**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.0

### Stack Trace

Uncaught Error: Config values to remove in 3.0:
The `esnext` option is enabled by default.
The `verbose` option is enabled by default.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

Error: Config values to remove in 3.0:
The `esnext` option is enabled by default.
The `verbose` option is enabled by default.
    at NodeConfiguration.Configuration._errorOnRemovedOptions (/Users/uni_mac/.dotfiles/atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:401:15)
    at NodeConfiguration.Configuration._processConfig (/Users/uni_mac/.dotfiles/atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:420:10)
    at NodeConfiguration.Configuration._loadPreset (/Users/uni_mac/.dotfiles/atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:635:10)
    at NodeConfiguration._loadPreset (/Users/uni_mac/.dotfiles/atom/packages/linter-jscs/node_modules/jscs/lib/config/node-configuration.js:160:41)
    at NodeConfiguration.Configuration._processConfig (/Users/uni_mac/.dotfiles/atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:485:14)
    at NodeConfiguration.Configuration.load (/Users/uni_mac/.dotfiles/atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:203:10)
    at [object Object].StringChecker.configure (/Users/uni_mac/.dotfiles/atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:62:29)
    at [object Object].Checker.configure (/Users/uni_mac/.dotfiles/atom/packages/linter-jscs/node_modules/jscs/lib/checker.js:28:39)
    at Function.fixString (/Users/uni_mac/.dotfiles/atom/packages/linter-jscs/src/linter-jscs.js:240:15)
    at /Users/uni_mac/.dotfiles/atom/packages/linter-jscs/src/linter-jscs.js:95:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -1:13.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-scss-lint"
    ]
  },
  "linter-jscs": {
    "esnext": true,
    "fixOnSave": true,
    "onlyConfig": true
  }
}
```

### Installed Packages

```coffee
# User
api-blueprint-preview, v0.7.0
atom-beautify, v0.29.7
atom-ember-author-kit, v0.6.6
auto-update-packages, v1.0.1
ember-snippets, v1.4.0
ember-tabs, v2.2.2
emmet, v2.4.3
file-icons, v1.7.9
jshint, v1.8.5
language-api-blueprint, v1.0.2
language-ember-htmlbars, v0.3.0
linter, v1.11.4
linter-api-blueprint, v0.4.0
linter-eslint, v7.2.2
linter-handlebars, v2.3.4
linter-jscs, v4.0.0
pigments, v0.26.2
project-manager, v2.9.7
tool-bar, v0.4.0
toolbar-basic, v0.3.1
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by aklkv** [comment]
Sorry found the problem with my preset [Upgrade jscs to 3.0 up](https://github.com/DockYard/ember-suave/issues/114)

**Comment by Arcanemagus** [comment]
Btw, thanks for being the only person so far to actually _read_ the error and realize what the problem was :stuck_out_tongue:.
