### ISSUE TITLE
Uncaught Error: Config values to remove in 3.0:The `esnext` option is enabled by default.

### ISSUE THREAD

**Issue by RiCoTeRoX** [AtomLinter/linter-jscs#232]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Ubuntu 14.04.4
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.0

### Stack Trace

Uncaught Error: Config values to remove in 3.0:
The `esnext` option is enabled by default.

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

Error: Config values to remove in 3.0:
The `esnext` option is enabled by default.
    at NodeConfiguration.Configuration._errorOnRemovedOptions (/home/danny/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:401:15)
    at NodeConfiguration.Configuration._processConfig (/home/danny/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:420:10)
    at NodeConfiguration.Configuration.load (/home/danny/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:203:10)
    at [object Object].StringChecker.configure (/home/danny/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:62:29)
    at [object Object].Checker.configure (/home/danny/.atom/packages/linter-jscs/node_modules/jscs/lib/checker.js:28:39)
    at Function.fixString (/home/danny/.atom/packages/linter-jscs/src/linter-jscs.js:250:4)
    at /home/danny/.atom/packages/linter-jscs/src/linter-jscs.js:95:18
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:28.4.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:28.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:27.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:27.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:25.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:25 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:23.8.0 core:undo (atom-text-editor.editor.mini.is-focused)
  3x -0:20.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:02.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:02.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:01.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-cocos2d-js",
      "autoprefixer",
      "goto"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "turbo-javascript",
      "compare-files"
    ]
  },
  "linter-jscs": {
    "configPath": ".jscsrc",
    "fixOnSave": true,
    "onlyConfig": true,
    "preset": "crockford"
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.1
custom-title, v1.0.1
file-icons, v1.7.9
highlight-selected, v0.11.2
jquery-snippets, v11.0.0
jshint, v1.8.5
linter, v1.11.4
linter-jscs, v4.0.0
merge-conflicts, v1.4.2
minimap, v4.23.5
minimap-highlight-selected, v4.4.0
package-sync, v1.1.0
pigments, v0.26.2
project-manager, v2.9.7
tabs-to-spaces, v1.0.2
underscorejs-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
This is caused by the upgrade to `jscs` v3.0.3 in the v4.0.0 update of this plugin, please read the error message and update your configuration accordingly, thanks!

**Comment by thrilleratwork** [comment]
Anyone who is still having this issue, I had to close and reload Atom before the errors went away.  I did not have esnext or other parse option set up in my .jscsrc nor was the ESNext config option enabled.  I think a parameter is lingering in memory after the update.

**Comment by Arcanemagus** [comment]
Ah, it's possible Atom isn't de-registering the old instance fully from linter when you update? Not sure but thanks for pointing that out!
