### ISSUE TITLE
Uncaught Error: Config values to remove in 3.0:The `esnext` option is enabled by default.

### ISSUE THREAD

**Issue by nixonlr** [AtomLinter/linter-jscs#233]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.0

### Stack Trace

Uncaught Error: Config values to remove in 3.0:
The `esnext` option is enabled by default.

```
At /Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

Error: Config values to remove in 3.0:
The `esnext` option is enabled by default.
    at NodeConfiguration.Configuration._errorOnRemovedOptions (/Users/nixon.ramin/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:401:15)
    at NodeConfiguration.Configuration._processConfig (/Users/nixon.ramin/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:420:10)
    at NodeConfiguration.Configuration.load (/Users/nixon.ramin/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:203:10)
    at [object Object].StringChecker.configure (/Users/nixon.ramin/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:62:29)
    at [object Object].Checker.configure (/Users/nixon.ramin/.atom/packages/linter-jscs/node_modules/jscs/lib/checker.js:28:39)
    at Function.fixString (/Users/nixon.ramin/.atom/packages/linter-jscs/src/linter-jscs.js:240:15)
    at /Users/nixon.ramin/.atom/packages/linter-jscs/src/linter-jscs.js:95:18
    at Function.module.exports.Emitter.simpleDispatch (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/nixon.ramin/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -7:33.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:17.8.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
  2x -0:10.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "linter-jscs": {
    "displayAs": "warning",
    "fixOnSave": true,
    "onlyConfig": true
  }
}
```

### Installed Packages

```coffee
# User
angular-2-typeScript-snippets, v0.2.1
atom-typescript, v8.9.1
linter, v1.11.4
linter-jscs, v4.0.0
linter-jshint, v2.1.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
This is caused by the upgrade to `jscs` v3.0.3 in the v4.0.0 update of this plugin, please read the error message and update your configuration accordingly, thanks!
