### ISSUE TITLE
Uncaught Error: Config values to remove in 3.0:The `esnext` option is enabled by default.

### ISSUE THREAD

**Issue by zerdos** [AtomLinter/linter-jscs#248]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0-beta3
**System**: Mac OS X 10.11.4
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.0

### Stack Trace

Uncaught Error: Config values to remove in 3.0:
The `esnext` option is enabled by default.

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:1002

Error: Config values to remove in 3.0:
The `esnext` option is enabled by default.
    at NodeConfiguration.Configuration._errorOnRemovedOptions (/Users/zoltan/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:401:15)
    at NodeConfiguration.Configuration._processConfig (/Users/zoltan/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:420:10)
    at NodeConfiguration.Configuration.load (/Users/zoltan/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:203:10)
    at [object Object].StringChecker.configure (/Users/zoltan/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:62:29)
    at [object Object].Checker.configure (/Users/zoltan/.atom/packages/linter-jscs/node_modules/jscs/lib/checker.js:28:39)
    at Function.fixString (/Users/zoltan/.atom/packages/linter-jscs/src/linter-jscs.js:240:15)
    at /Users/zoltan/.atom/packages/linter-jscs/src/linter-jscs.js:95:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:01.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "terminal-plus"
    ],
    "packagesWithKeymapsDisabled": [
      "tree-view"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai-seti"
    ]
  },
  "linter-jscs": {
    "fixOnSave": true,
    "onlyConfig": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
jshint, v1.8.5
linter, v1.11.4
linter-jscs, v4.0.0
linter-scss-lint, v3.0.3
minimap, v4.23.5
monokai-seti, v0.7.0
platformio-ide-terminal, v2.0.9

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Please read the error message.

You have a configuration value in your `.jscsrc` file that is no longer allowed as of JSCS v3.

If for some reason you are unable to use JSCS v3 then you can run `apm install linter-jscs@3.5.0` to use the last version on the JSCS v2 branch.
