### ISSUE TITLE
Uncaught Error: Parse error on line 1:{<<<<<<< HEAD  "name-^Expecting 'STRING', '}', [git conflict]

### ISSUE THREAD

**Issue by RiCoTeRoX** [AtomLinter/linter-jscs#254]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Ubuntu 14.04.4
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.1

### Stack Trace

Uncaught Error: Parse error on line 1:
{<<<<<<< HEAD  "name
-^
Expecting 'STRING', '}', got 'undefined'

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

Error: Parse error on line 1:
{<<<<<<< HEAD  "name
-^
Expecting 'STRING', '}', got 'undefined'
    at Object.parseError (/home/danny/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/home/danny/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/home/danny/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/home/danny/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/home/danny/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /home/danny/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/home/danny/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/home/danny/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/home/danny/.atom/packages/linter-jscs/src/linter-jscs.js:226:27)
    at /home/danny/.atom/packages/linter-jscs/src/linter-jscs.js:99:31
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -3:35.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:43.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:43.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:03.2.0 core:copy (atom-text-editor.editor.is-focused)
     -1:57.8.0 core:paste (atom-text-editor.editor.is-focused)
     -1:56.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:56.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:55.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:54.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:54.5.0 core:cancel (atom-text-editor.editor.is-focused)
  3x -1:36.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:33 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:33 core:cancel (atom-text-editor.editor.is-focused)
     -1:28.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:57.6.0 core:cancel (a.btn-issue.btn.btn-error)
  2x -0:55.2.0 core:save (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-cocos2d-js",
      "autoprefixer",
      "goto",
      "tool-bar-main"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "turbo-javascript",
      "compare-files"
    ]
  },
  "linter-jscs": {
    "configPath": ".jscsrc",
    "fixOnSave": true,
    "onlyConfig": true,
    "preset": "crockford"
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.1
custom-title, v1.0.1
file-icons, v1.7.11
highlight-selected, v0.11.2
jquery-snippets, v11.0.0
jshint, v1.8.5
linter, v1.11.4
linter-jscs, v4.0.1
linter-sass-lint, v1.5.0
merge-conflicts, v1.4.2
minimap, v4.23.5
minimap-highlight-selected, v4.4.0
package-sync, v1.1.0
pigments, v0.26.3
project-manager, v2.9.7
tabs-to-spaces, v1.0.2
tool-bar, v0.4.0
tool-bar-almighty, v0.6.1
underscorejs-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Your `.jscsrc` file is invalid JSON, fix that and that error should go away. (There is another issue open already for handling that error better.)
