### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Nicola-Nardella** [AtomLinter/linter-jscs#255]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Ubuntu 16.04
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.2
### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /home/cicas/.atom/packages/linter-jscs/src/linter-jscs.js:100

TypeError: Cannot read property 'id' of undefined
  at /home/cicas/.atom/packages/linter-jscs/src/linter-jscs.js:97:51
  at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at TextBuffer.module.exports.TextBuffer.saveAs (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
  at TextBuffer.module.exports.TextBuffer.save (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
  at TextEditor.module.exports.TextEditor.save (/opt/atom/resources/app.asar/src/text-editor.js:660:26)
  at AtomRunner.execute (/home/cicas/.atom/packages/atom-runner/lib/atom-runner.coffee:146:14)
  at AtomRunner.run (/home/cicas/.atom/packages/atom-runner/lib/atom-runner.coffee:122:6)
  at atom-workspace.<anonymous> (/home/cicas/.atom/packages/atom-runner/lib/atom-runner.coffee:81:57)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:98:36)
  at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)

```
### Commands

```
     -0:52.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:52.9.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:52.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:51.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:50.4.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:50.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:49.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:49.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:49.2.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:49.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:47.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:46.2.0 core:save (atom-text-editor.editor.is-focused)
 12x -0:43 core:select-down (atom-text-editor.editor.is-focused)
     -0:40.4.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:40.4.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
  4x -0:38 run:file (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-alignment, v0.12.1
atom-runner, v2.6.0
atom-ternjs, v0.14.1
autocomplete-go, v1.1.0
autocomplete-json, v1.10.0
autocomplete-modules, v1.4.1
builder-go, v1.0.0
docblockr, v0.7.3
environment, v1.2.0
file-icons, v1.7.12
go-config, v1.1.4
go-debug, v0.1.12
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
js-hyperclick, v1.4.2
js-refactor, v0.6.0
language-babel, v2.22.0
language-ini, v1.16.0
language-latex, v0.6.1
language-ocaml, v1.1.2
language-thrift, v1.0.2
latex, v0.32.0
latex-autocomplete, v0.4.3
latex-plus, v0.8.7
latexer, v0.3.0
linter, v1.11.4
linter-chktex, v1.3.0
linter-jscs, v4.0.2
navigator-godef, v1.0.3
node-debugger, v1.7.0
nuclide, v0.138.0
pdf-view, v0.50.0
polymer-atom, v0.0.8
refactor, v0.6.0
set-syntax, v0.3.0
tag, v0.4.0
tester-go, v1.0.4
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Can you describe what you were doing when you triggered this?

**Comment by cicas86** [comment]
When I build my js with ALT+R I received this issue, but if I press again ALT+R it works

**Comment by Arcanemagus** [comment]
Atom doesn't have anything by default bound to that, so you must be using some other package to "build" your JS? It sounds like it might be doing odd things with editors...

**Comment by flaviocamilo** [comment]
The same happens to me. The plugin used alongside is atom-runner, that binds to Alt-R (Win/Linux) and Ctrl-R (Mac).
Also on Atom 1.8.0.

**Comment by Sam2304** [comment]
+1 I've also hit this with the same two packages...

**Comment by Arcanemagus** [comment]
Hmmm, there is nothing obvious in their code that could be causing this, I'll try to get some time to debug later this unless somebody else figures out what is going on.

**Comment by schwin97** [comment]
I believe this is occurring because linter-jscs is trying to check the syntax on the window opened by atom-runner.  Is there any way to block linter-jscs from automatically attempting to check the syntax?

**Comment by bronson** [comment]
I get this when I click on other windows so Atom gets sent to the background.

Perhaps `atom.workspace.getActiveTextEditor()` returns undefined in that case?

**Comment by Juuro** [comment]
I get this when trying to find and replace in project.

**Comment by Arcanemagus** [comment]
If anyone wants to tackle this feel free to submit a PR, as JSCS development is entirely dead I'm not planning on dedicating any major time to this package. If nobody feels like taking this on my current plan is to just remove the fix-on-save functionality as it has been nothing but buggy the entire time it has existed.

You should be looking into moving to a linter that is currently maintained, such as ESLint (where the JSCS team moved to).

**Comment by Arcanemagus** [comment]
Closing this as nobody that is still using JSCS has taken the time to dig into this, as described above you should be [moving to ESLint](https://eslint.org/docs/user-guide/migrating-from-jscs), however if somebody wants to submit a PR here I can get it merged.
