### ISSUE TITLE
Column start(1) greater than line length(0)

### ISSUE THREAD

**Issue by crucialfelix** [AtomLinter/linter-jscs#259]
### Version
Atom 1.7.4
linter-jscs 4.0.2

### Issue
I'm not sure yet how this starts, but once it starts then every file save will throw the red error up. There is no option to report the error as usual.

It may be something to do with JavaScript (JSX)  - these files have react markup in them.

There are no jscs errors on the page; there are some eslint warnings.

source code is here: https://gist.github.com/crucialfelix/12781e3d807c4cf8c672d93c4ea1a1b2

but this happens with other files as well and has been happening for a week or so.

```
Error: Column start (1) greater than line length (0)
    at Object.rangeFromLineNumber (/Users/crucial/.atom/packages/linter-eslint/node_modules/atom-linter/lib/index.js:194:11)
    at /Users/crucial/.atom/packages/linter-jscs/src/linter-jscs.js:217:33
    at Array.map (native)
    at Object.lint (/Users/crucial/.atom/packages/linter-jscs/src/linter-jscs.js:212:41)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/crucial/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/crucial/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/crucial/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/crucial/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/crucial/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by Arcanemagus** [comment]
Managed to break this down into the following repo case: [linter-jscs_GH259.zip](https://github.com/AtomLinter/linter-jscs/files/291711/linter-jscs_GH259.zip)

![image](https://cloud.githubusercontent.com/assets/427137/15683300/78b24d44-2716-11e6-9182-919427106a83.png)
As you can see this is an issue in `jscs` itself. Note that on the last error it's pointing well past the end of the line, and the error before that is pointing to the entirely wrong place (but isn't triggering this warning since it is still within the confines of the line).

Do you want to file an issue on JSCS about this or should I?

**Comment by crucialfelix** [comment]
i will do it. thanks for the detective work. i guess that explains why the error wasnt handled. do you want to add exception handling during the jcsc call ?    sorry for one handed typing.

**Comment by Arcanemagus** [comment]
That error is actually thrown from `atom-linter` when invalid ranges are fed into it, I put it in there _specifically_ to catch issues like this where the linter is providing invalid input.

If a linter is giving invalid input I feel it should be fixed there so everyone using it benefits, rather than ignoring it here. After all if you can't trust the linter to give back valid ranges, why are you using it in the first place? :stuck_out_tongue:

**Comment by crucialfelix** [comment]
Sure, but why didn't Atom catch the error and offer to file an issue ? That means it was outside that event loop, right ?

**Comment by Arcanemagus** [comment]
The error wasn't being thrown from JSCS, but from `atom-linter` [here](https://github.com/steelbrain/atom-linter/blob/v5.0.1/src/index.js#L43). As to why Atom didn't offer to file an issue I'm not sure.

**Comment by crucialfelix** [comment]
OK, thanks. I'll file an issue with jcsc tomorrow and then close this one.

**Comment by crucialfelix** [comment]
https://github.com/jscs-dev/node-jscs/issues/2261

Thanks again and thanks for the package. I guess jscs is merging with eslint now.
