### ISSUE TITLE
Toast error on save

### ISSUE THREAD

**Issue by eswak** [AtomLinter/linter-jscs#263]
### Version
linter-jscs: 4.0.2

### Issue
When I save files (lint on save is enabled), I get the following toast error : 

**Atom Version**: 1.7.4
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.2

### Stack Trace

Uncaught Error: Config values to remove in 3.0:
The `esnext` option is enabled by default.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

Error: Config values to remove in 3.0:
The `esnext` option is enabled by default.
    at NodeConfiguration.Configuration._errorOnRemovedOptions (/Users/erwan/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:401:15)
    at NodeConfiguration.Configuration._processConfig (/Users/erwan/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:420:10)
    at NodeConfiguration.Configuration.load (/Users/erwan/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:203:10)
    at [object Object].StringChecker.configure (/Users/erwan/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:62:29)
    at [object Object].Checker.configure (/Users/erwan/.atom/packages/linter-jscs/node_modules/jscs/lib/checker.js:28:39)
    at Function.fixString (/Users/erwan/.atom/packages/linter-jscs/src/linter-jscs.js:230:15)
    at /Users/erwan/.atom/packages/linter-jscs/src/linter-jscs.js:89:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -3:48.6.0 core:close (atom-text-editor.editor.is-focused.power-mode)
     -3:18.4.0 application:add-project-folder (atom-text-editor.editor.power-mode)
     -2:57.3.0 git-plus:pull-using-rebase (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:45.2.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:37.1.0 editor:consolidate-selections (atom-text-editor.editor.power-mode.is-focused)
     -2:37.1.0 core:cancel (atom-text-editor.editor.power-mode.is-focused)
     -2:28 find-and-replace:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:26.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:25.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:25.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:23.8.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -0:07.7.0 core:copy (atom-text-editor.editor.power-mode.is-focused)
     -0:04.6.0 core:save (atom-text-editor.editor.power-mode.is-focused)
  2x -0:03.9.0 editor:consolidate-selections (atom-text-editor.editor.power-mode.is-focused)
     -0:03.0 core:cancel (atom-text-editor.editor.power-mode.is-focused)
     -0:00.8.0 core:save (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "deprecation-cop",
      "highlight-css-color",
      "git-log",
      "git-projects",
      "html-helper",
      "line-count",
      "preview",
      "tool-bar-main",
      "tree-view"
    ],
    "followSymlinks": true,
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "node_modules",
      "bower_components"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-mocha",
      "mocha-runner",
      "bracket-matcher",
      "activate-power-mode",
      "git-control"
    ],
    "projectHome": "/src"
  },
  "linter-jscs": {
    "configPath": "/src/.jscsrc",
    "fixOnSave": true,
    "onlyConfig": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
autoclose-html, v0.23.0
autocomplete-paths, v1.0.2
git-commit, v1.5.2
git-plus, v5.14.0
highlight-line, v0.11.1
linter, v1.11.4
linter-jscs, v4.0.2
linter-jshint, v2.1.0
minimap, v4.24.3
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-pigments, v0.2.1
pigments, v0.29.1
save-session, v0.16.0
tool-bar, v0.4.0
tool-bar-config, v0.0.2
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
If you read the error message, you can see that your configuration file is specifying the `esnext` option, which is no longer allowed as of `jscs@3`. If you remove that option it should work properly.
