### ISSUE TITLE
Error: Config values to remove in 3.0: The `verbose` option is enabled by default.

### ISSUE THREAD

**Issue by arun1595** [AtomLinter/linter-jscs#321]
### Version
4.1.1

### Stacktrace

```
Error: Config values to remove in 3.0:
The `verbose` option is enabled by default.
    at NodeConfiguration.Configuration._errorOnRemovedOptions (/home/lazyass/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:445:15)
    at NodeConfiguration.Configuration._processConfig (/home/lazyass/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:464:10)
    at NodeConfiguration.Configuration.load (/home/lazyass/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:211:10)
    at Checker.configure (/home/lazyass/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:62:29)
    at Checker.configure (/home/lazyass/.atom/packages/linter-jscs/node_modules/jscs/lib/checker.js:27:39)
    at Object.lint (/home/lazyass/.atom/packages/linter-jscs/src/linter-jscs.js:257:14)
    at promises.push.Promise.then._this.emitter.emit.linter (/home/lazyass/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /home/lazyass/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/home/lazyass/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /home/lazyass/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /home/lazyass/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1154:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1124:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:871:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:738:18)
    at Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:693:35)
    at atom-workspace.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:222:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:584:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:379:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:59)
```

**Comment by Arcanemagus** [comment]
Please read the message you posted 😛.

It looks like you have a `verbose` setting in your `jscs.rc` file, which is no longer a valid configuration option in JSCS v3.
