### ISSUE TITLE
Uncaught Error: Parse error on line 15:...env $(cat .env)",  },  "repository": {---------------...

### ISSUE THREAD

**Issue by jeffmiralles** [AtomLinter/linter-jscs#325]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package 4.1.1

### Stack Trace

Uncaught Error: Parse error on line 15:
...env $(cat .env)",  },  "repository": {
----------------------^
Expecting 'STRING', got '}'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1045

Error: Parse error on line 15:
...env $(cat .env)",  },  "repository": {
----------------------^
Expecting 'STRING', got '}'
    at Object.parseError (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at /packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at getConfig (/packages/linter-jscs/src/linter-jscs.js:47:25)
    at /packages/linter-jscs/src/linter-jscs.js:176:26
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1060:20)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:891:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:22.2.0 core:move-down (input.hidden-input)
     -1:21.7.0 core:move-up (input.hidden-input)
     -1:20.8.0 core:move-left (input.hidden-input)
     -1:20.7.0 editor:move-to-first-character-of-line (input.hidden-input)
 23x -1:20.5.0 core:move-right (input.hidden-input)
     -1:18.8.0 core:backspace (input.hidden-input)
     -1:18.6.0 core:save (input.hidden-input)
     -1:18.3.0 core:move-down (input.hidden-input)
     -1:17.7.0 core:move-up (input.hidden-input)
     -1:16.5.0 core:backspace (input.hidden-input)
     -1:16.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:15.9.0 core:move-left (input.hidden-input)
     -1:15.5.0 core:backspace (input.hidden-input)
     -1:15.2.0 core:save (input.hidden-input)
  7x -1:13.5.0 core:undo (input.hidden-input)
  2x -1:10.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-jshint 2.0.0 
atom-ternjs 0.14.1 
linter 1.11.23 
linter-jscs 4.1.1 
```

**Comment by Arcanemagus** [comment]
Looks like you have a trailing comma in your `package.json`.

**Comment by jeffmiralles** [comment]
thanks, solved
