### ISSUE TITLE
Uncaught Error: Parse error on line 19:...path": "^0.12.7",  },  "FH": {    "po----------------...

### ISSUE THREAD

**Issue by ascsi** [AtomLinter/linter-jscs#330]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package 4.1.2

### Stack Trace

Uncaught Error: Parse error on line 19:
...path": "^0.12.7",  },  "FH": {    "po
----------------------^
Expecting 'STRING', got '}'

```
At C:\Users\Allan Schytt\AppData\Local\atom\app-1.14.4\resources\app.asar\src\pane.js:1045

Error: Parse error on line 19:
...path": "^0.12.7",  },  "FH": {    "po
----------------------^
Expecting 'STRING', got '}'
    at Object.parseError (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at /packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at getConfig (/packages/linter-jscs/src/linter-jscs.js:47:25)
    at /packages/linter-jscs/src/linter-jscs.js:185:26
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1060:20)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:893:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -3:41.6.0 application:open-folder (input.hidden-input)
     -2:32.4.0 application:add-project-folder (input.hidden-input)
     -2:24.6.0 application:open-folder (input.hidden-input)
     -1:21.5.0 core:copy (input.hidden-input)
     -1:13.8.0 core:paste (input.hidden-input)
     -1:02.3.0 core:copy (input.hidden-input)
  2x -1:00.6.0 core:paste (input.hidden-input)
  5x -0:55.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
.bin undefined 
atom-beautify 0.29.17 
atom-typescript 10.1.14 
bottom-dock 0.4.4 
git-plus 7.3.3 
grunt-runner 0.14.0 
linter 1.11.23 
linter-jscs 4.1.2 
linter-jshint 3.0.3 
linter-less 2.6.0 
linter-manager 0.2.12 
linter-tidy 2.3.0 
open-on-bitbucket 0.4.0 
Remote-FTP 0.10.7 
remote-sync 4.1.5 
```

**Comment by Arcanemagus** [comment]
You have a trailing comma in your `package.json`, from the little bit of context it looks like in your `dependencies` section.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
