### ISSUE TITLE
Uncaught Error: Parse error on line 6:...: "Andrew Maxwell",}----------------------^Expecting ...

### ISSUE THREAD

**Issue by amaxwell01** [AtomLinter/linter-jscs#334]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package 4.1.2

### Stack Trace

Uncaught Error: Parse error on line 6:
...: "Andrew Maxwell",}
----------------------^
Expecting 'STRING', got '}'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1045

Error: Parse error on line 6:
...: "Andrew Maxwell",}
----------------------^
Expecting 'STRING', got '}'
    at Object.parseError (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at /packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at getConfig (/packages/linter-jscs/src/linter-jscs.js:47:25)
    at /packages/linter-jscs/src/linter-jscs.js:185:26
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1059:20)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1048:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:915:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:31.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-one-dark-syntax.theme-atom-material-ui)
     -0:13.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 1.3.9 
autocomplete 0.47.0 
build 0.67.0 
busy 0.7.0 
editorconfig 2.2.2 
file-icons 2.1.1 
git-blame 0.4.12 
git-plus 7.3.3 
language-javascript-jsx 0.3.7 
linter 2.1.2 
linter-eslint 8.1.4 
linter-jscs 4.1.2 
nuclide 0.209.0 
pigments 0.39.1 
pretty-json 1.6.1 
project-manager 3.3.4 
set-syntax 0.3.2 
sort-lines 0.14.0 
```

**Comment by Arcanemagus** [comment]
You have a trailing comma in your `package.json`.

Also, all development on JSCS has stopped, I would _highly_ recommend you move on to ESLint.
