### ISSUE TITLE
Uncaught Error: Parse error on line 15:...  "dependencies": {<<<<<<< HEAD    "wh---------------...

### ISSUE THREAD

**Issue by michaelmena** [AtomLinter/linter-jscs#337]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package 4.1.2

### Stack Trace

Uncaught Error: Parse error on line 15:
...  "dependencies": {<<<<<<< HEAD    "wh
----------------------^
Expecting 'STRING', '}', got 'undefined'

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:1095

Error: Parse error on line 15:
...  "dependencies": {<<<<<<< HEAD    "wh
----------------------^
Expecting 'STRING', '}', got 'undefined'
    at Object.parseError (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at /packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at getConfig (/packages/linter-jscs/src/linter-jscs.js:47:25)
    at /packages/linter-jscs/src/linter-jscs.js:185:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1119:26)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:780:24)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:57.5.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:49.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:09.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.2 
atom-css-comb 3.1.0 
atom-html-preview 0.1.22 
atom-jade 0.3.0 
atom-runner 2.7.1 
autoclose-html 0.23.0 
browser-plus 0.0.97 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.7 
highlight-selected 0.13.1 
intentions 1.1.2 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
linter 2.2.0 
linter-jscs 4.1.2 
linter-jshint 3.1.2 
linter-ui-default 1.6.2 
minimap 4.28.2 
node-debugger 1.10.1 
open-in-browser 0.5.2 
pigments 0.39.1 
```

**Comment by Arcanemagus** [comment]
This is coming from JSCS's `package.json` parser (during a merge conflict resolution it looks like). For some bizarre reason JSCS decided it would be a good idea to completely blow up instead of handling an invalid config gracefully. Nothing that can be done about it here.
