### ISSUE TITLE
Uncaught Error: Parse error on line 6:...ailingComma": null, optional	"validate---------------...

### ISSUE THREAD

**Issue by adithyamahesh596** [AtomLinter/linter-jscs#339]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Education
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package 4.1.2

### Stack Trace

Uncaught Error: Parse error on line 6:
...ailingComma": null, optional
	"validate
-----------------------^
Expecting 'STRING', got 'undefined'

```
At C:\Users\AdithyaMaheshBariki\AppData\Local\atom\app-1.18.0\resources\app\src\pane.js:1095

Error: Parse error on line 6:
...ailingComma": null, optional
	"validate
-----------------------^
Expecting 'STRING', got 'undefined'
    at Object.parseError (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/packages/linter-jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:88:31)
    at Object.exports.load (/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:139:20)
    at getConfig (/packages/linter-jscs/src/linter-jscs.js:47:25)
    at /packages/linter-jscs/src/linter-jscs.js:185:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1119:26)
    at TextBuffer.module.exports.TextBuffer.save (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:780:24)
    at Pane.saveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (~/AppData/Local/atom/app-1.18.0/resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -9:35.2.0 editor:newline (input.hidden-input)
  6x -9:34.8.0 core:move-left (input.hidden-input)
  4x -9:32.9.0 core:move-right (input.hidden-input)
     -9:31.1.0 core:move-down (input.hidden-input)
     -9:03.2.0 core:move-right (input.hidden-input)
     -9:00.0 editor:newline (input.hidden-input)
  2x -8:43 core:backspace (input.hidden-input)
     -8:33.4.0 core:move-right (input.hidden-input)
 29x -8:29.7.0 core:move-left (input.hidden-input)
 32x -8:27.8.0 core:move-right (input.hidden-input)
     -8:16.9.0 core:move-left (input.hidden-input)
     -8:16.1.0 editor:newline (input.hidden-input)
  2x -8:02.2.0 core:move-right (input.hidden-input)
     -8:01.4.0 core:move-left (input.hidden-input)
     -7:58.9.0 intentions:highlight (input.hidden-input)
     -7:58.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-jshint 2.0.0 
atom-jshinter 0.1.3 
busy-signal 1.4.3 
intentions 1.1.2 
jshint 1.8.6 
linter 2.2.0 
linter-jscs 4.1.2 
linter-jshint 3.1.4 
linter-ui-default 1.6.2 
```

**Comment by Arcanemagus** [comment]
Your `package.json` is invalid, causing JSCS's internal JSON linter to throw an error.

JSCS is no longer being developed I would _highly_ recommend you move to ESLint for linting your code!
