### ISSUE TITLE
Uncaught Error: Cannot find module 'source-map-support'

### ISSUE THREAD

**Issue by bahubal** [AtomLinter/linter-jscs#345]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package 4.1.3

### Stack Trace

Uncaught Error: Cannot find module 'source-map-support'

```
At C:\Users\HP\AppData\Local\atom\app-1.22.0\resources\app\static\<embedded>:1

Error: Cannot find module 'source-map-support'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-jscs/node_modules/cst/lib/index.js:98:25)
    at /packages/linter-jscs/node_modules/cst/lib/index.js:113:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-jscs/node_modules/jscs/lib/token-assert.js:3:13)
    at /packages/linter-jscs/node_modules/jscs/lib/token-assert.js:413:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-jscs/node_modules/jscs/lib/errors.js:2:19)
    at /packages/linter-jscs/node_modules/jscs/lib/errors.js:357:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Commands

```
     -0:20.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-live-server 2.2.0 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.13 
intentions 1.1.5 
linter 2.2.0 
linter-jscs 4.1.3 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-pigments 0.2.2 
pigments 0.40.2 
todo 0.6.0 
```

**Comment by Arcanemagus** [comment]
Can you try re-installing this package?

Also, please note that JSCS development is officially dead, you should investigate switching to ESLint 😉.
