### ISSUE TITLE
Error running JSCS Error: Column start (1) greater than line length (0) for line 2

### ISSUE THREAD

**Issue by borisovg** [AtomLinter/linter-jscs#347]
### Version
Atom: 1.24.1
Plugin: 4.1.3 

### Issue

Example code:
```
console.log(`\n`);
foo
```

There seems to be some sort of breakage triggered by template string with new line character. If there is subsequently a line of code with a JSCS error (like the "Missing semicolon after statement" for line 2) then an error is thrown in the debug console:

```
[Linter] Error running JSCS Error: Column start (1) greater than line length (0) for line 2
    at Object.generateRange (/home/borisov/.atom/packages/linter-jshint/node_modules/atom-linter/lib/index.js:181:11)
    at /home/borisov/.atom/packages/linter-jscs/src/linter-jscs.js:299:33
    at Array.map (native)
    at Object.lint (/home/borisov/.atom/packages/linter-jscs/src/linter-jscs.js:294:41)
    at promises.push.Promise.then._this2.emitter.emit.number (/home/borisov/.atom/packages/linter/lib/linter-registry.js:101:24)
    at _loop (/home/borisov/.atom/packages/linter/lib/linter-registry.js:99:21)
    at LinterRegistry.<anonymous> (/home/borisov/.atom/packages/linter/lib/linter-registry.js:87:40)
    at Generator.next (<anonymous>)
    at LinterRegistry.<anonymous> (/home/borisov/.atom/packages/linter/lib/linter-registry.js:143:4)
    at Generator.next (<anonymous>)
    at step (/home/borisov/.atom/packages/linter/lib/linter-registry.js:5:273)
    at /home/borisov/.atom/packages/linter/lib/linter-registry.js:5:443
    at LinterRegistry.<anonymous> (/home/borisov/.atom/packages/linter/lib/linter-registry.js:5:99)
    at /home/borisov/.atom/packages/linter/lib/main.js:125:30
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /home/borisov/.atom/packages/linter/lib/editor-linter.js:26:20
    at later (/home/borisov/.atom/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

JSCS settings:

```
{
    "preset"                                    : "airbnb",
    "disallowMultipleSpaces"                    : true,
    "disallowMultipleVarDecl"                   : { "allExcept": ["undefined"] },
    "disallowSpacesInFunctionDeclaration"       : false,
    "disallowSpacesInNamedFunctionExpression"   : false,
    "disallowTabs"                              : true,
    "maximumLineLength"                         : false,
    "requireCamelCaseOrUpperCaseIdentifiers"    : false,
    "requireSpacesInFunction"                   : { "beforeOpeningRoundBrace": true, "beforeOpeningCurlyBrace": true },
    "validateIndentation"                       : 4,
    "validateLineBreaks"                        : "LF"
}
```

**Comment by Arcanemagus** [comment]
That's due to JSCS reporting a point that doesn't actually exist in the document. Since _all_ development on JSCS has stopped, this will _never_ be fixed. You should look into switching to a modern JS linter such as ESLint (where the JSCS team moved).

**Comment by borisovg** [comment]
If this is not going to be fixed, perhaps the ticket should be kept open, so that the growing list of visible "wontfix" will put people from using it?

Also a *deprecation notice* would be good to have in the README.

**Comment by Arcanemagus** [comment]
JSCS itself has notices plastered everywhere, I figured that if somebody is using it they must have a _really_ good reason to do so (company policy?).

If you want to send in a PR updating the README that would be great though 😉.
