### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ok2ju** [AtomLinter/linter-jscs#37]
1. Open Atom
2. Create new tab
3. Select 'JavaScript' language

**Atom Version**: 0.186.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v1.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At C:\Users\ok2ju\.atom\packages\linter-jscs\lib\linter-jscs.coffee:36

TypeError: Cannot read property 'split' of undefined
  at new LinterJscs (C:\Users\ok2ju\.atom\packages\linter-jscs\lib\linter-jscs.coffee:36:15)
  at LinterView.initLinters (C:\Users\ok2ju\.atom\packages\linter\lib\linter-view.coffee:51:27)
  at C:\Users\ok2ju\.atom\packages\linter\lib\linter-view.coffee:103:8
  at Emitter.module.exports.Emitter.emit (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.handleGrammarChange (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\src\text-editor.js:2831:27)
  at C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\src\text-editor.js:200:24
  at Emitter.module.exports.Emitter.emit (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\src\tokenized-buffer.js:168:27)
  at DisplayBuffer.module.exports.DisplayBuffer.setGrammar (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\src\display-buffer.js:1058:35)
  at TextEditor.module.exports.TextEditor.setGrammar (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\src\text-editor.js:2436:33)
  at GrammarListView.module.exports.GrammarListView.confirmed (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\node_modules\grammar-selector\lib\grammar-list-view.js:60:21)
  at GrammarListView.module.exports.SelectListView.confirmSelection (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\ok2ju\AppData\Local\atom\app-0.186.0\resources\app\src\window-event-handler.js:182:20)

```

### Commands

```
     -2:16.5 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:17.7 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:15.1 grammar-selector:show (atom-text-editor.editor)
     -0:13.4 core:move-down (atom-text-editor.editor.mini)
     -0:13.1 core:confirm (atom-text-editor.editor.mini)
     -0:09.4 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:09.4 core:cancel (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "linter-jscs": {}
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.4
linter, v0.12.0
linter-jscs, v1.8.0
linter-jshint, v0.1.0
linter-scss-lint, v0.0.14

# Dev
No dev packages
```

**Comment by iam4x** [comment]
Thank's for error reporting, fix in next release.
