### ISSUE TITLE
Failed to activate the linter-jscs package

### ISSUE THREAD

**Issue by gj747467491** [AtomLinter/linter-jscs#419]
### Version
X.X.X

### Issue
Describe Your Issue
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package 4.2.2

### Stack Trace

Failed to activate the linter-jscs package

```
At (0 , _util.promisify) is not a function

TypeError: (0 , _util.promisify) is not a function
    at /packages/linter-jscs/node_modules/sb-fs/lib/index.js:17:46
    at Array.forEach (native)
    at /packages/linter-jscs/node_modules/sb-fs/lib/index.js:13:26)
    at /packages/linter-jscs/node_modules/sb-fs/lib/index.js:51:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:87:30)
    at /app.asar/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/app.asar/src/native-compile-cache.js:47:27)
    at /packages/linter-jscs/node_modules/atom-package-deps/lib/helpers.js:10:36)
    at /packages/linter-jscs/node_modules/atom-package-deps/lib/helpers.js:196:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:87:30)
    at /app.asar/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/app.asar/src/native-compile-cache.js:47:27)
    at /packages/linter-jscs/node_modules/atom-package-deps/lib/index.js:10:39)
    at /packages/linter-jscs/node_modules/atom-package-deps/lib/index.js:55:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:87:30)
    at /app.asar/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/app.asar/src/native-compile-cache.js:47:27)
    at Object.activate (/packages/linter-jscs/src/linter-jscs.js:142:5)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:251:19)
    at /app.asar/src/package.js:1028:28
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at triggeredActivationHooks.forEach.hook (/app.asar/src/package-manager.js:695:80)
    at Set.forEach (native)
    at PackageManager.activatePackage (/app.asar/src/package-manager.js:695:37)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:521:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -2:20.7.0 core:paste (input.hidden-input)
  2x -2:17.7.0 core:confirm (input.hidden-input)
  5x -2:13.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
alios-studio 1.2.6 
atom-beautify 0.33.4 
atom-ternjs 0.19.1 
busy-signal 2.0.1 
docblockr 0.13.7 
emmet 2.4.3 
intentions 1.1.5 
linter 2.3.0 
linter-eslint 8.5.5 
linter-jscs 4.2.2 
linter-jshint 3.1.16 
linter-ui-default 1.7.1 
simplified-chinese-menu 5.3.5 
```

**Comment by Arcanemagus** [comment]
> Atom: 1.21.1 x64

You're running an out of date version of Atom, please update to the current version.
