### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by maxrosecollins** [AtomLinter/linter-jscs#90]
[Enter steps to reproduce below:]

Updated atom to 1.0.5
Got the following error.

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v2.0.4

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn ENOTDIR
    at exports._errnoException (util.js:734:11)
    at ChildProcess.spawn (child_process.js:1145:11)
    at Object.exports.spawn (child_process.js:977:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at /Users/max/.atom/packages/linter-jscs/node_modules/atom-linter/lib/helpers.coffee:100:28
    at Object.module.exports.Helpers._exec (/Users/max/.atom/packages/linter-jscs/node_modules/atom-linter/lib/helpers.coffee:57:14)
    at Object.module.exports.Helpers.exec (/Users/max/.atom/packages/linter-jscs/node_modules/atom-linter/lib/helpers.coffee:27:19)
    at Object.lint (/Users/max/.atom/packages/linter-ruby/lib/main.js:43:24)
    at Promise.then._this.emitter.emit.linter (/Users/max/.atom/packages/linter/lib/linter-registry.coffee:95:31)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "linter-jscs": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-ruby, v0.1.0
linter, v1.3.2
linter-clojure, v0.0.5
linter-coffeelint, v1.0.2
linter-csslint, v1.0.2
linter-erb, v0.1.1
linter-htmlhint, v0.0.17
linter-jscs, v2.0.4
linter-jsonlint, v0.1.4
linter-less, v2.0.3
linter-reek, v2.0.0
linter-rubocop, v0.2.7
linter-ruby, v1.0.0
linter-scss-lint, v2.0.0
linter-tidy, v1.0.1
react, v0.12.6

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
@maxrosecollins are you still seeing this issue? That error is most likely from a codebase that has been moved on from...

**Comment by casesandberg** [comment]
@maxrosecollins Are you still seeing this? More than likely it is no longer a bug.

**Comment by Arcanemagus** [comment]
With no response to the original prompt I'm just marking this as closed, @maxrosecollins if you are still seeing this feel free to file a new issue so we can work on fixing it :wink:.
